[package]
name = "redis-lite"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.4"
once_cell = "1.18"
parking_lot = "0.12" # optional, faster Mutex/RwLock
clap = { version = "4", features = ["derive"] }

